name: Update the container NoedJS

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Check
        uses: actions/checkout@v2
      -      
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: amenimaamouri/uvt-devops:1.0.${{github.run_number}}
      - 
        name: Check NodeJS
        uses: actions/checkout@v2 
      - 
        name: Run NodeJS Test
        uses: actions/setup-node@v3
        with:
         node-version: 18
      - 
        name: Install jest
        run: npm install
   
      - 
        name: Test
        run: npm test

