name: pipeline app NoedJS

on:
  push:
    branches:
      - 'main'

jobs:
  build-deploy:
     runs-on: ubuntu-latest
     steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Check
        uses: actions/checkout@v2
      -      
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: amenimaamouri/uvt-devops:1.0.${{github.run_number}}

  test:
     runs-on: ubuntu-latest
     needs: build-deploy
     steps:      
      - 
        name: Check NodeJS
        uses: actions/checkout@v2 
      - 
        name: Run NodeJS Test
        uses: actions/setup-node@v3
        with:
         node-version: 18
      - 
        name: Install jest
        run: npm install
      - 
        name: Test
        run: npm test

  deploy-to-azure-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with: 
          node-version: '18.x'
      - name: Install Dependencies
        run: npm install
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: backend-App
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: . 
